import React, { useEffect, useState } from 'react';
import { ShieldCheck, RefreshCw, Edit3, ArrowRight, Sparkles, CheckCircle, Layers, Target, Megaphone, Compass, Palette } from 'lucide-react';
import { api } from '../services/api';

interface BusinessBlueprintReviewProps {
  businessId: string;
  onApproved: () => void;
  onEditAnswers: () => void;
}

export const BusinessBlueprintReview: React.FC<BusinessBlueprintReviewProps> = ({
  businessId,
  onApproved,
  onEditAnswers,
}) => {
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);
  const [approving, setApproving] = useState(false);
  const [blueprintRecord, setBlueprintRecord] = useState<any>(null);
  const [history, setHistory] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);

  const loadBlueprint = async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await api.getBusinessBlueprint(businessId);
      if (res && res.active) {
        setBlueprintRecord(res.active);
      } else if (res && res.history && res.history.length > 0) {
        setBlueprintRecord(res.history[0]);
      }
      if (res && res.history) {
        setHistory(res.history);
      }
    } catch (err: any) {
      setError(err.message || 'Failed to load Business Blueprint');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (businessId) {
      loadBlueprint();
    }
  }, [businessId]);

  const handleApprove = async () => {
    try {
      setApproving(true);
      await api.approveBusinessBlueprint(businessId, blueprintRecord?.id);
      onApproved();
    } catch (err: any) {
      alert(`Approval failed: ${err.message}`);
    } finally {
      setApproving(false);
    }
  };

  const handleRegenerate = async () => {
    try {
      setRegenerating(true);
      const res = await api.regenerateBusinessBlueprint(businessId);
      if (res) {
        setBlueprintRecord(res);
        await loadBlueprint();
      }
    } catch (err: any) {
      alert(`Regeneration failed: ${err.message}`);
    } finally {
      setRegenerating(false);
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', minHeight: '100vh', justifyContent: 'center', alignItems: 'center', background: 'var(--color-bg-end)' }}>
        <div style={{ textAlign: 'center', color: 'var(--color-text-muted)' }}>
          <Sparkles size={40} className="animate-spin" style={{ color: 'var(--color-primary)', marginBottom: 16 }} />
          <h3>Generating Business Blueprint & Strategy...</h3>
          <p style={{ fontSize: '0.85rem' }}>Our AI Consultant Agent is processing your 14 onboarding answers.</p>
        </div>
      </div>
    );
  }

  const bp = blueprintRecord?.blueprint;

  return (
    <div style={{ minHeight: '100vh', background: 'var(--color-bg-end)', padding: '40px 8%' }}>
      {/* Top Banner */}
      <div className="glass-panel" style={{ padding: 24, borderRadius: 16, marginBottom: 32, display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16 }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
            <span style={{ fontSize: '1.4rem' }}>🏛️</span>
            <h2 style={{ margin: 0, fontSize: '1.4rem' }}>AI Business Blueprint & Marketing Strategy</h2>
            <span style={{
              fontSize: '0.75rem',
              padding: '2px 10px',
              borderRadius: 12,
              background: blueprintRecord?.approved ? 'rgba(16, 185, 129, 0.2)' : 'rgba(245, 158, 11, 0.2)',
              color: blueprintRecord?.approved ? '#10b981' : '#f59e0b',
              fontWeight: 600,
              border: blueprintRecord?.approved ? '1px solid #10b981' : '1px solid #f59e0b',
            }}>
              Version {blueprintRecord?.version || 'v1'} ({blueprintRecord?.approved ? 'APPROVED' : 'PENDING APPROVAL'})
            </span>
          </div>
          <p style={{ margin: 0, color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>
            Generated by Business Consultant Agent • Central Intelligence Foundation for Visionpilot AI ({history.length} versions recorded)
          </p>
        </div>

        <div style={{ display: 'flex', gap: 12 }}>
          <button className="btn-secondary" onClick={onEditAnswers} style={{ padding: '10px 16px', display: 'flex', alignItems: 'center', gap: 6 }}>
            <Edit3 size={16} /> Edit Answers
          </button>
          <button className="btn-secondary" onClick={handleRegenerate} disabled={regenerating} style={{ padding: '10px 16px', display: 'flex', alignItems: 'center', gap: 6 }}>
            <RefreshCw size={16} className={regenerating ? 'animate-spin' : ''} />
            {regenerating ? 'Regenerating...' : 'Regenerate'}
          </button>
          <button className="btn-primary" onClick={handleApprove} disabled={approving} style={{ padding: '10px 24px', display: 'flex', alignItems: 'center', gap: 8, background: '#10b981' }}>
            <CheckCircle size={18} />
            {approving ? 'Approving...' : 'Approve & Launch Dashboard'}
          </button>
        </div>
      </div>

      {error && (
        <div style={{ padding: 16, background: 'rgba(239, 68, 68, 0.15)', border: '1px solid #ef4444', color: '#ef4444', borderRadius: 12, marginBottom: 24 }}>
          {error}
        </div>
      )}

      {/* Blueprint Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 24 }}>
        
        {/* Executive Summary */}
        <div className="glass-panel" style={{ padding: 24, borderRadius: 16, gridColumn: '1 / -1' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--color-primary)', marginBottom: 12 }}>
            <Compass size={20} />
            <h3 style={{ margin: 0 }}>Executive Business Summary</h3>
          </div>
          <p style={{ color: 'var(--color-text)', lineHeight: 1.6, margin: 0 }}>
            {bp?.executiveSummary || 'No summary generated.'}
          </p>
        </div>

        {/* SWOT Analysis Matrix */}
        <div className="glass-panel" style={{ padding: 24, borderRadius: 16, gridColumn: '1 / -1' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--color-primary)', marginBottom: 16 }}>
            <ShieldCheck size={20} />
            <h3 style={{ margin: 0 }}>SWOT Analysis Grid</h3>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 16 }}>
            <div style={{ background: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.3)', padding: 16, borderRadius: 12 }}>
              <h4 style={{ color: '#10b981', marginTop: 0 }}>💪 Strengths</h4>
              <ul style={{ margin: 0, paddingLeft: 20, fontSize: '0.85rem' }}>
                {bp?.swot?.strengths?.map((s: string, i: number) => <li key={i}>{s}</li>)}
              </ul>
            </div>
            <div style={{ background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.3)', padding: 16, borderRadius: 12 }}>
              <h4 style={{ color: '#ef4444', marginTop: 0 }}>⚠️ Weaknesses</h4>
              <ul style={{ margin: 0, paddingLeft: 20, fontSize: '0.85rem' }}>
                {bp?.swot?.weaknesses?.map((w: string, i: number) => <li key={i}>{w}</li>)}
              </ul>
            </div>
            <div style={{ background: 'rgba(59, 130, 246, 0.1)', border: '1px solid rgba(59, 130, 246, 0.3)', padding: 16, borderRadius: 12 }}>
              <h4 style={{ color: '#3b82f6', marginTop: 0 }}>🚀 Opportunities</h4>
              <ul style={{ margin: 0, paddingLeft: 20, fontSize: '0.85rem' }}>
                {bp?.swot?.opportunities?.map((o: string, i: number) => <li key={i}>{o}</li>)}
              </ul>
            </div>
            <div style={{ background: 'rgba(245, 158, 11, 0.1)', border: '1px solid rgba(245, 158, 11, 0.3)', padding: 16, borderRadius: 12 }}>
              <h4 style={{ color: '#f59e0b', marginTop: 0 }}>🛡️ Threats</h4>
              <ul style={{ margin: 0, paddingLeft: 20, fontSize: '0.85rem' }}>
                {bp?.swot?.threats?.map((t: string, i: number) => <li key={i}>{t}</li>)}
              </ul>
            </div>
          </div>
        </div>

        {/* Customer Persona & Pain Points */}
        <div className="glass-panel" style={{ padding: 24, borderRadius: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--color-primary)', marginBottom: 12 }}>
            <Target size={20} />
            <h3 style={{ margin: 0 }}>Ideal Customer Persona</h3>
          </div>
          <p style={{ fontSize: '0.85rem', lineHeight: 1.5 }}>
            {bp?.idealCustomerPersona?.summary}
          </p>
          <div style={{ marginTop: 12 }}>
            <strong>Demographics:</strong>
            <div style={{ fontSize: '0.8rem', color: 'var(--color-text-muted)', marginTop: 4 }}>
              Age: {bp?.idealCustomerPersona?.ageGroup} | Gender: {bp?.idealCustomerPersona?.gender}
            </div>
          </div>
          <div style={{ marginTop: 12 }}>
            <strong>Pain Points:</strong>
            <ul style={{ paddingLeft: 20, fontSize: '0.8rem', margin: '4px 0 0 0' }}>
              {bp?.customerPainPoints?.map((p: string, i: number) => <li key={i}>{p}</li>)}
            </ul>
          </div>
          <div style={{ marginTop: 12 }}>
            <strong>Buying Triggers:</strong>
            <ul style={{ paddingLeft: 20, fontSize: '0.8rem', margin: '4px 0 0 0' }}>
              {bp?.buyingTriggers?.map((b: string, i: number) => <li key={i}>{b}</li>)}
            </ul>
          </div>
        </div>

        {/* Marketing Strategy & Channels */}
        <div className="glass-panel" style={{ padding: 24, borderRadius: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--color-primary)', marginBottom: 12 }}>
            <Megaphone size={20} />
            <h3 style={{ margin: 0 }}>Marketing Strategy</h3>
          </div>
          <p style={{ fontSize: '0.85rem', lineHeight: 1.5 }}>
            {bp?.marketingStrategy}
          </p>
          <div style={{ marginTop: 16 }}>
            <strong>Recommended Marketing Channels:</strong>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 8 }}>
              {bp?.recommendedChannels?.map((ch: string, i: number) => (
                <span key={i} style={{ padding: '4px 10px', borderRadius: 12, background: 'rgba(99, 102, 241, 0.15)', fontSize: '0.75rem', color: '#818cf8' }}>
                  {ch}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Content Pillars & Campaign Strategy */}
        <div className="glass-panel" style={{ padding: 24, borderRadius: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--color-primary)', marginBottom: 12 }}>
            <Layers size={20} />
            <h3 style={{ margin: 0 }}>Content & Ad Strategy</h3>
          </div>
          <div style={{ marginBottom: 12 }}>
            <strong>Content Pillars:</strong>
            <ul style={{ paddingLeft: 20, fontSize: '0.8rem', margin: '4px 0 0 0' }}>
              {bp?.contentPillars?.map((cp: string, i: number) => <li key={i}>{cp}</li>)}
            </ul>
          </div>
          <div style={{ marginTop: 12 }}>
            <strong>Campaign Objective:</strong> {bp?.campaignStrategy?.objective}
          </div>
          <div style={{ marginTop: 6, fontSize: '0.8rem', color: 'var(--color-text-muted)' }}>
            <strong>Messaging Hook:</strong> "{bp?.campaignStrategy?.messagingHook}"
          </div>
        </div>

        {/* Brand Voice & Ad Budget */}
        <div className="glass-panel" style={{ padding: 24, borderRadius: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--color-primary)', marginBottom: 12 }}>
            <Palette size={20} />
            <h3 style={{ margin: 0 }}>Brand Voice & Guidelines</h3>
          </div>
          <div>
            <strong>Tone:</strong> {bp?.brandVoice?.tone}
          </div>
          <div style={{ marginTop: 8, fontSize: '0.85rem' }}>
            <strong>Style:</strong> {bp?.brandVoice?.messagingStyle}
          </div>
          <div style={{ marginTop: 12, padding: 12, background: 'rgba(255, 255, 255, 0.03)', borderRadius: 8, fontSize: '0.8rem' }}>
            <strong>Budget Breakdown:</strong>
            <p style={{ margin: '4px 0 0 0', color: 'var(--color-text-muted)' }}>
              {bp?.suggestedAdStrategy?.budgetAllocation}
            </p>
          </div>
        </div>

      </div>

      {/* Bottom Approval Footer */}
      <div style={{ marginTop: 40, textAlign: 'center' }}>
        <button className="btn-primary" onClick={handleApprove} disabled={approving} style={{ padding: '16px 40px', fontSize: '1rem', background: '#10b981' }}>
          <CheckCircle size={20} style={{ marginRight: 8 }} />
          Approve Blueprint & Unlock Performance Dashboard <ArrowRight size={18} style={{ marginLeft: 8 }} />
        </button>
      </div>
    </div>
  );
};
